# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    binary: sshs
    main: ./cmd/sshs/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 5
      - 6
      - 7
archives:
  - id: sshs
    replacements:
      darwin: macOS
      linux: Linux
      amd64: x86_64
      windows: Windows

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
